server.port=${SERVER_PORT:8761}

spring.application.name=eureka-server

# Eureka standalone mode
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${SERVER_PORT:8761}/eureka

# Self-preservation & eviction
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Actuator & Logging
logging.file.name=logs/eureka-server.log
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
